name: Deploy JMeter Results to GitHub Pages

on:
  push:
    branches:
      - Hammock  # Trigger deployment only on the Hammock branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'

    - name: Build/Copy the HTML content to the deployment folder
      run: |
        mkdir -p gh-pages  # Create a new folder for deployment
        cp -r html/* gh-pages/  # Copy contents from the html directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        folder: gh-pages
        target_branch: gh-pages
        commit_message: 'Deploy JMeter test results'
        github_token: ${{ secrets.GITHUB_TOKEN }}
